# Generated by Django 4.1.4 on 2023-03-17 13:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_lesson', models.IntegerField()),
                ('start_time', models.TimeField(default=datetime.datetime(2023, 3, 17, 8, 0))),
                ('end_time', models.TimeField(default=datetime.datetime(2023, 3, 17, 8, 45))),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('date_of_enrollment', models.DateField()),
                ('payment_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_months', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSubject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('date_of_enrollment', models.DateField()),
                ('work_experience', models.IntegerField()),
                ('admission_year', models.IntegerField()),
                ('mail', models.CharField(max_length=50)),
                ('number_phone', models.CharField(max_length=20)),
                ('number_whatsapp', models.CharField(max_length=20)),
                ('date_certification', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gender')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nation')),
                ('teachSubj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subjectlesson')),
            ],
        ),
        migrations.AddField(
            model_name='subjectlesson',
            name='teachers',
            field=models.ManyToManyField(to='main.teacher'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class')),
                ('lesson_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lessontime')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to='main.student'),
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(to='main.teacher'),
        ),
    ]
