# Generated by Django 3.2.16 on 2023-03-11 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_lesson', models.IntegerField()),
                ('start_time', models.TimeField(default=datetime.datetime(2023, 3, 11, 8, 0))),
                ('end_time', models.TimeField(default=datetime.datetime(2023, 3, 11, 8, 45))),
            ],
        ),
        migrations.DeleteModel(
            name='Times',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_time',
            field=models.ManyToManyField(to='main.LessonTime'),
        ),
    ]
