# Generated by Django 4.1.4 on 2023-03-19 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_subjectlesson_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontime',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 19, 8, 45)),
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 19, 8, 0)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mail',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_experience',
            field=models.IntegerField(blank=True),
        ),
    ]
