# Generated by Django 3.2.16 on 2023-03-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230311_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.lessontime'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
