# Generated by Django 3.2.16 on 2023-03-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230311_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSubject', models.CharField(max_length=100)),
            ],
        ),
    ]
