# Generated by Django 3.2.16 on 2023-03-11 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_subjectlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teachSubj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.subjectlesson'),
            preserve_default=False,
        ),
    ]
