# Generated by Django 3.2.16 on 2023-03-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230311_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.accesslevel'),
        ),
    ]
