# Generated by Django 3.2.16 on 2023-03-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_adminlogentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminLogEntry',
        ),
    ]
