# Generated by Django 3.2.16 on 2023-03-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_adminlogentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='AUTH_USER_MODEL',
        ),
    ]
