# Generated by Django 3.2.16 on 2023-03-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_user_profile_auth_user_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='AUTH_USER_MODEL',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
