# Generated by Django 3.2.16 on 2023-03-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20230312_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectlesson',
            name='teachers',
            field=models.ManyToManyField(to='main.Teacher'),
        ),
    ]
